name: Build

on: [push, pull_request]

jobs:
  lint:
    name: Lint & Doc
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: 24.x

    - name: Install dependencies
      run: npm install --location=global bslint @hns-dev/bsdoc

    - name: Install bslintrc
      run: npm install bslintrc

    - name: Lint
      run: npm run lint

    - name: Docs
      run: npm run build-docs

  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: 24.x

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libunbound-dev |
           npm install nyc coveralls

    - name: Test
      run: npm run test-ci

    - name: Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  build-test:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x, 18.x, 20.x, 22.x, 24.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Install libunbound
      if: contains(matrix.os, 'ubuntu')
      run: sudo apt-get update && sudo apt-get install -y libunbound-dev

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm test
